apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: addressbook
 name: addressbook
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: addressbook
  spec:
   containers:
   - image: preciousonyekwere/addressbooks:latest
     name: addressbooks
     ports:
     - containerPort: 6443
     env:
     - name: ALLOW_EMPTY_PASSWORD
       value: yes
 selector:
  matchLabels:
   app: addressbook
