apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: addressbook
 name: addressbook
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: addressbook
  spec:
   containers:
   - image: preciousonyekwere/addbook:latest
     name: addressbooks
     ports:
     - containerPort: 2222
 selector:
  matchLabels:
   app: addressbook
